# fly.toml app configuration file generated for kitty-bot on 2023-08-11T16:19:22-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kitty-bot"
primary_region = "atl"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
